sudo: require 
services:
    - docker 

before_install:
    - docker build -t nimaadocker/docker-react-infra -f Dockerfile.dev .

script:
    - docker run nimaadocker/docker-react-infra npm run test -- --coverage  

